name: run-test
on: [push]
jobs:
    mix-test:
        runs-on: ubuntu-latest
        container:
            image: elixir:1.12
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
        - uses: actions/checkout@v3
        - run: mix deps.get
        - run: mix test
            env:
                POSTGRES_HOST: postgres
                POSTGRES_PORT: 5432
